version: 2.1

executors:
  playwright-executor:
    docker:
      - image: mcr.microsoft.com/playwright:v1.38.0-focal
        environment:
          DISPLAY: ":99"  # Настройка дисплея для графического режима
    working_directory: ~/repo

jobs:
  run-tests:
    executor: playwright-executor
    steps:
      - checkout

      - run:
          name: Установка зависимостей
          command: |
            apt-get update && apt-get install -y xvfb
            npm install

      - run:
          name: Установка браузеров Playwright
          command: npx playwright install

      - run:
          name: Запуск тестов Playwright в headed режиме
          command: |
            Xvfb :99 &  # Запуск виртуального дисплея
            npx playwright test --headed

      - store_artifacts:
          path: playwright-report
          destination: playwright-report
workflows:
  run-tests-workflow:
    jobs:
      - run-tests
