name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        group: [1, 2, 3, 4, 5]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Setup virtual display
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Run Playwright tests for Group ${{ matrix.group }}
        env:
          GROUP: ${{ matrix.group }}
        run: xvfb-run -a npx playwright test demo.spec.ts GROUP=$GROUP

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: html-report-group-${{ matrix.group }}
          path: playwright-report
          retention-days: 30
